// Generated by CoffeeScript 1.10.0
(function() {
  var cache, fs, mkdirp, userHome, yaml;

  fs = require('fs');

  mkdirp = require('mkdirp');

  userHome = require('user-home');

  yaml = require('js-yaml');

  cache = function(key, val, debug) {
    var crystal, crystal_file, crystal_path;
    crystal_path = userHome + "/.autocode/";
    crystal_file = crystal_path + "crystal.yml";
    crystal = fs.existsSync(crystal_file) ? yaml.safeLoad(fs.readFileSync(crystal_file)) : {};
    if (!crystal.cache) {
      crystal.cache = {};
    }
    if (val !== void 0) {
      crystal.cache[key] = val;
      fs.writeFileSync(crystal_file, yaml.safeDump(crystal));
    }
    if (debug) {
      console.log("File:   " + crystal_file);
      console.log("Method: crystal.cache(key, val)");
      console.log("Key:    " + key);
      console.log("Value:  " + crystal.cache[key] + "\n");
    }
    return crystal.cache[key];
  };

  module.exports = cache;

}).call(this);
