// Generated by CoffeeScript 1.10.0
(function() {
  var fs;

  fs = require('fs-extra');

  module.exports = function(opts) {
    console.log('Cleaning...');
    fs.removeSync('lib');
    return console.log('Done.');
  };

}).call(this);
