// Generated by CoffeeScript 1.10.0
(function() {
  module.exports = function(singular, plural) {
    var cases, change, changecase, format, pluralize;
    changecase = require('change-case');
    pluralize = require('pluralize');
    if (!singular || !singular.length) {
      throw new Error('"singular" is required in crystal.build.format()');
    }
    plural = plural || pluralize(singular);
    cases = ['camel', 'constant', 'dot', 'lower', 'param', 'pascal', 'path', 'sentence', 'snake', 'swap', 'title', 'ucFirst', 'upper'];
    change = function(str) {
      var c, changes, i, len;
      changes = {};
      for (i = 0, len = cases.length; i < len; i++) {
        c = cases[i];
        changes[c.toLowerCase()] = changecase[c](str);
      }
      return changes;
    };
    format = change(singular);
    format.plural = change(plural);
    return format;
  };

}).call(this);
