// Generated by CoffeeScript 1.10.0
(function() {
  var autocode;

  autocode = require('../autocode');

  module.exports = function(opts) {
    var config, imported;
    if (opts == null) {
      opts = {};
    }
    opts.ignoreOverwrite = true;
    imported = this.install(opts);
    config = this.load(process.cwd());
    if (!config.imports) {
      config.imports = {};
    }
    config.imports[imported.name] = "~" + imported.version;
    return this.save({
      config: config
    });
  };

}).call(this);
