// Generated by CoffeeScript 1.9.3
(function() {
  var fs, path, skeemas, validate, yaml;

  fs = require('fs');

  path = require('path');

  skeemas = require('skeemas');

  yaml = require('js-yaml');

  validate = function(config) {
    var config_schema, crystal_path;
    crystal_path = path.resolve(__dirname + "/../..");
    config_schema = yaml.safeLoad(fs.readFileSync(crystal_path + "/.autocode/schema/config.yml"));
    validate = skeemas.validate(config, config_schema);
    return validate;
  };

  module.exports = validate;

}).call(this);
