// Generated by CoffeeScript 1.9.3
(function() {
  module.exports = function(opts) {
    var crystal, i, runCmd, scripts, spawn;
    crystal = this;
    spawn = require('cross-spawn');
    this.build(opts);
    if (!this.project.scripts || !this.project.scripts.run) {
      return 'Nothing to run.';
    }
    scripts = this.project.scripts;
    i = 0;
    runCmd = function() {
      var arg, cmd, proc, run, runInterval;
      if (!scripts.run[i]) {
        return 'Done.';
      }
      run = scripts.run[i];
      run = [run.substr(0, run.indexOf(' ')), run.substr(run.indexOf(' ') + 1)];
      cmd = run[0];
      arg = run[1].split(' ');
      proc = spawn(cmd, arg);
      proc.stdout.on('data', function(data) {
        return console.log(data.toString());
      });
      proc.on('exit', function(err) {
        return runCmd();
      });
      proc.on('error', function(err) {
        return console.log('run error', err);
      });
      runInterval = setInterval((function() {
        if (crystal.stopped) {
          console.log('Project was stopped.');
          crystal.stopped = false;
          clearInterval(runInterval);
          return proc.kill();
        }
      }), 1);
      return i++;
    };
    runCmd();
    return 'Running...';
  };

}).call(this);
