// Generated by CoffeeScript 1.10.0
(function() {
  module.exports = function(msg) {
    var args, error, vsprintf;
    vsprintf = require('sprintf').vsprintf;
    args = [].slice.apply(arguments);
    args.shift();
    error = vsprintf(msg, args);
    throw new Error(error);
  };

}).call(this);
