// Generated by CoffeeScript 1.10.0
(function() {
  module.exports = function(version) {
    var findVersions, versions;
    findVersions = require('find-versions');
    versions = findVersions(version, {
      loose: true
    });
    if (!versions.length) {
      return null;
    }
    return version = versions[0];
  };

}).call(this);
