import { generate } from '@specui/core';
import { PrettierProcessor } from '@specui/prettier';

export default async function output() {
  return await generate({
    processor: PrettierProcessor(),
    engine: async () => /* ts */ `
      import type { Metadata } from 'next'
      import { Inter } from 'next/font/google'
      import './globals.css'
      
      const inter = Inter({ subsets: ['latin'] })
      
      export const metadata: Metadata = {
        title: 'Create Next App',
        description: 'Generated by create next app',
      }
      
      export default function RootLayout({
        children,
      }: {
        children: React.ReactNode
      }) {
        return (
          <html lang="en">
            <body className={inter.className}>{children}</body>
          </html>
        )
      }
    `,
  });
}
