// Generated by CoffeeScript 1.10.0
(function() {
  module.exports = function() {
    var file, fs, text;
    return "\nAUTOCODE\n========\n";
    fs = require('fs');
    file = __dirname + "/../ascii.txt";
    text = fs.readFileSync(file);
    if (!text) {
      throw new Error("Unable to load ASCII text from " + file);
    }
    return text = text.toString();
  };

}).call(this);
